version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/maven@1.0.2
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: circleci/maven@1.0.2
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test